### ISSUE TITLE
Crashes adapting Unity app to Skyworth

### ISSUE THREAD

**Issue by santiimageen** [skyworthvr/SkyworthXR.Plugin.SDK#1]
When I try to use SkyworthXR Plugin I have a crash getting this errors in logcat:

11-03 16:19:23.319   542   565 E vulkan  : invalid vkGetInstanceProcAddr(VK_NULL_HANDLE, "vkEnumerateInstanceVersion") call
11-03 16:19:23.336  1660  1677 E BufferQueueProducer: [SurfaceView - net.imageen.player/com.unity3d.player.UnityPlayerActivity] connect: already connected (cur=1 req=1)
11-03 16:19:25.088   791   791 E memtrack: Couldn't load memtrack module (No such file or directory)
11-03 16:19:25.088   791   791 E android.os.Debug: failed to load memtrack module: -2
11-03 16:19:25.135   542   565 E XrApi   : /system/priv-app/SvrService/SvrService.apk!/assets/libxrcore64.so not available: dlopen failed: library "/system/priv-app/SvrService/SvrService.apk!/assets/libxrcore64.so" not found

**Comment by zhgyee** [comment]
Which device are you using? This is a legacy SDK for old devices like S802/V901.

**Comment by santiimageen** [comment]
Skyworth S801

**Comment by zhgyee** [comment]
S801 SDK is not open source, please try this link:
https://drive.google.com/file/d/1y-HAD3iCBCzaJOvCV_jbK71wnHgWHKht/view?usp=sharing

**Comment by zhgyee** [comment]
closed

**Comment by santiimageen** [comment]
Thanks. Do you have documentation or anything else  about this SDK?
I don't get it to work with ARM64

**Comment by zhgyee** [comment]
https://drive.google.com/drive/folders/1HsBQO1MerolpetyBApfxafBwQMtxxIAJ?usp=sharing
Please try the new SDK with the sample,note that this SDK only works for ARM32
